apiVersion: v1
kind: Service
metadata:
  name: you-take-home-app-service
  annotations:                                                                                                                                                                                                                                                                        
    # service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:200495214320:certificate/8ff3efc9-073d-4831-a70c-90c3533cf962
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: you-app 
spec:
  selector:
    app: you-app 

  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000            

  type: LoadBalancer
